# Generated by Django 4.1.7 on 2023-03-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('user_pw', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_area', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_title', models.CharField(max_length=255)),
                ('sale_content', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('image', models.ImageField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onion.user')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_content', models.TextField()),
                ('date', models.DateTimeField(null=True)),
                ('sale_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onion.sale')),
            ],
        ),
    ]
